version: '3.1'

# docker-compose up
# docker rm $(docker ps -a -q) && docker volume prune -f

services:

  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "12345678"
      MYSQL_DATABASE: agileProject
    ports:
      - '3306:3306'
    volumes:
      - './schema/:/docker-entrypoint-initdb.d/'